### ISSUE TITLE
bino3d Flathub Package on rpi5

### ISSUE THREAD

**Issue by hubertmeier** [flathub/org.bino3d.bino#4]
the maintainer of pi-apps rejected the app request for bino3d with the following text:

Closing as unable to support. QT6.6 is not available in the default repositories for any of the distros we support.

The flatpak package is available but cannot be used due to the following issue that affects all versions of the application: If upstream fixes their software to automatically use the appropriate GL/GLES renderer based on what the drivers report as available this can be reopened. As it is now, the application does not work out of the box.

is there a way, to start the Flathub Package with the --opengles parameter?

Thank you

**Comment by marlam** [comment]
My plan is to automatically select OpenGL ES when Desktop GL does not provide sufficient features, so that the --opengles option is not necessary.

It is unfortunate that the rpi5 ships with such a broken graphics configuration. They should have disabled Desktop OpenGL altogether instead of shipping a broken/outdated version.

**Comment by hubertmeier** [comment]
Ok, thank you. Are you still interested to have a vnc access to a fresh rpi5 bookworm installation?

**Comment by marlam** [comment]
Yes please! I really need to test on that platform to make sure the next release will work flawlessly.

**Comment by hubertmeier** [comment]
Did you receive the account data for my rpi5 yesterday per Mail?

**Comment by marlam** [comment]
An update to 2.3 is underway, and it should work on rpi5 out of the box.
